// CommonJS mirror of client/src/utils/exercises.js — used by /api/exercises
const EXERCISES = [
  // ── Strength ───────────────────────────────────────────
  {
    id: 1, name: 'Bench Press', cat: 'strength', muscle: 'chest',
    bodyPart: 'chest', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 10,
    instructions: [
      'Set up the barbell at chest height on the rack.',
      'Lie flat on the bench with your eyes directly under the bar.',
      'Grip the bar slightly wider than shoulder-width with an overhand grip.',
      'Plant your feet flat on the floor and arch your lower back slightly.',
      'Unrack the bar and move it over your chest.',
      'Lower the bar slowly to your mid-chest (2–3 sec).',
      'Press the bar back up explosively to full extension.',
      'Re-rack the bar after completing all reps.',
    ],
    tips: [
      'Keep shoulder blades squeezed together throughout.',
      'Don\'t bounce the bar off your chest — control the descent.',
      'Drive your feet into the floor for stability.',
      'Use a spotter or safety bars when lifting heavy.',
    ],
  },
  {
    id: 2, name: 'Incline Dumbbell Press', cat: 'strength', muscle: 'chest',
    bodyPart: 'chest', difficulty: 'intermediate', equipment: 'dumbbell',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Set an adjustable bench to a 30–45° incline.',
      'Sit with a dumbbell in each hand resting on your thighs.',
      'Lean back and lift the dumbbells to shoulder level, palms facing forward.',
      'Press the dumbbells up until arms are fully extended above your upper chest.',
      'Lower the dumbbells slowly back to shoulder level.',
      'Repeat for the desired number of reps.',
    ],
    tips: [
      'A 30° incline targets the upper chest more than 45°.',
      'Keep dumbbells in line with your upper chest, not your shoulders.',
      'Control the lowering phase — don\'t let gravity do the work.',
    ],
  },
  {
    id: 3, name: 'Push-up', cat: 'strength', muscle: 'chest',
    bodyPart: 'chest', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Start in a high plank with hands slightly wider than shoulder-width.',
      'Keep your body in a straight line from head to heels — engage your core.',
      'Lower your chest toward the floor by bending your elbows at about 45°.',
      'Stop just before your chest touches the floor.',
      'Push back up explosively to the starting position.',
      'Breathe in on the way down, breathe out on the way up.',
    ],
    tips: [
      'Don\'t let your hips sag or pike — keep a rigid plank position.',
      'For an easier variation, drop to your knees.',
      'For harder variation, elevate your feet on a bench.',
    ],
  },
  {
    id: 4, name: 'Pull-up', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'intermediate', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 8,
    instructions: [
      'Grab a pull-up bar with an overhand grip, hands shoulder-width apart.',
      'Hang with arms fully extended and shoulders engaged.',
      'Pull your chest toward the bar by driving your elbows down.',
      'Squeeze your back muscles at the top.',
      'Lower yourself slowly until your arms are fully extended.',
      'Repeat without swinging.',
    ],
    tips: [
      'Initiate the movement by retracting your shoulder blades first.',
      'Avoid kipping or swinging for strict strength gains.',
      'If you can\'t do full pull-ups, use a resistance band for assistance.',
    ],
  },
  {
    id: 5, name: 'Lat Pulldown', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'beginner', equipment: 'machine',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit at the lat pulldown machine and adjust the thigh pad.',
      'Grip the bar wider than shoulder-width with an overhand grip.',
      'Lean back slightly and pull the bar down to your upper chest.',
      'Squeeze your lats at the bottom.',
      'Slowly return the bar to the starting position.',
      'Repeat without letting the weight stack crash.',
    ],
    tips: [
      'Avoid pulling the bar behind your neck — this strains your cervical spine.',
      'Keep your chest up and core braced throughout.',
    ],
  },
  {
    id: 6, name: 'Bent-Over Row', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 10,
    instructions: [
      'Stand with feet shoulder-width apart, barbell on the floor.',
      'Hinge at the hips until your torso is nearly parallel to the floor.',
      'Grip the bar slightly wider than shoulder-width.',
      'Pull the bar to your lower chest/upper abdomen, leading with your elbows.',
      'Squeeze your back at the top.',
      'Lower the bar with control.',
    ],
    tips: [
      'Keep your back flat — don\'t round your lower back.',
      'Brace your core the entire time.',
      'Keep the bar close to your body throughout the movement.',
    ],
  },
  {
    id: 7, name: 'Deadlift', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'advanced', equipment: 'barbell',
    defaultSets: 4, defaultReps: 5,
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot.',
      'Hinge at the hips and grip the bar just outside your legs.',
      'Drop your hips, lift your chest, and brace your core.',
      'Push the floor away as you lift — don\'t think of it as pulling.',
      'Lock out at the top by squeezing your glutes.',
      'Hinge back down under control to reset.',
    ],
    tips: [
      'Keep the bar in contact with your body the entire lift.',
      'Never round your lower back — neutral spine is critical.',
      'Warm up thoroughly before heavy deadlifts.',
    ],
  },
  {
    id: 8, name: 'Barbell Squat', cat: 'strength', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 4, defaultReps: 8,
    instructions: [
      'Set the barbell at upper chest height on the rack.',
      'Step under and rest it on your upper traps (high bar) or rear delts (low bar).',
      'Step back, feet shoulder-width apart with toes slightly out.',
      'Brace your core and descend by pushing knees out and hips back.',
      'Lower until your thighs are at least parallel to the floor.',
      'Drive back up through your heels to standing.',
    ],
    tips: [
      'Keep your chest up and avoid leaning too far forward.',
      'Push your knees out in the direction of your toes.',
      'Depth first — then add weight.',
    ],
  },
  {
    id: 9, name: 'Leg Press', cat: 'strength', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'machine',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit on the leg press machine and place feet shoulder-width apart on the platform.',
      'Release the safety handles.',
      'Lower the platform by bending your knees to about 90°.',
      'Press the platform away until legs are almost fully extended (don\'t lock out).',
      'Repeat with control.',
    ],
    tips: [
      'Keep your lower back pressed into the seat.',
      'Don\'t let your knees cave inward.',
      'Foot position higher = more hamstrings/glutes; lower = more quads.',
    ],
  },
  {
    id: 10, name: 'Lunges', cat: 'strength', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Stand tall with feet together.',
      'Step forward with one foot, landing heel first.',
      'Lower your back knee toward the floor until front thigh is parallel to ground.',
      'Push off your front foot to return to starting position.',
      'Alternate legs for each rep.',
    ],
    tips: [
      'Keep your front knee directly above your ankle, not past your toes.',
      'Maintain an upright torso — don\'t lean forward.',
      'Add dumbbells to increase difficulty.',
    ],
  },
  {
    id: 11, name: 'Shoulder Press', cat: 'strength', muscle: 'shoulders',
    bodyPart: 'shoulders', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 10,
    instructions: [
      'Set the barbell at collar-bone height on a rack.',
      'Grip the bar just outside shoulder-width.',
      'Unrack and hold it at shoulder level.',
      'Press the bar straight up overhead until arms are fully extended.',
      'Lower the bar back to shoulder level with control.',
    ],
    tips: [
      'Brace your core and squeeze your glutes to protect your lower back.',
      'Keep your wrists stacked over your elbows.',
      'Avoid arching your lower back excessively.',
    ],
  },
  {
    id: 12, name: 'Lateral Raise', cat: 'strength', muscle: 'shoulders',
    bodyPart: 'shoulders', difficulty: 'beginner', equipment: 'dumbbell',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Stand with feet shoulder-width apart, dumbbells at your sides.',
      'With a slight bend in the elbows, raise both arms out to the sides.',
      'Lift until arms are parallel to the floor (shoulder height).',
      'Lower slowly — take 3 seconds on the way down.',
    ],
    tips: [
      'Lead with your elbows, not your wrists.',
      'Slightly tilt the dumbbells as if pouring water — little finger slightly higher.',
      'Use lighter weight and focus on control over momentum.',
    ],
  },
  {
    id: 13, name: 'Bicep Curl', cat: 'strength', muscle: 'biceps',
    bodyPart: 'arms', difficulty: 'beginner', equipment: 'dumbbell',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Stand holding dumbbells at your sides, palms facing forward.',
      'Keeping your elbows pinned to your sides, curl the dumbbells toward your shoulders.',
      'Squeeze your biceps at the top.',
      'Lower slowly back to starting position.',
    ],
    tips: [
      'Avoid swinging your body — only your forearms should move.',
      'Full range of motion gives better results than partial reps.',
      'Supinate (rotate) your wrists as you curl for full bicep activation.',
    ],
  },
  {
    id: 14, name: 'Tricep Pushdown', cat: 'strength', muscle: 'triceps',
    bodyPart: 'arms', difficulty: 'beginner', equipment: 'cable',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Attach a straight bar or rope to a high cable pulley.',
      'Stand facing the machine, grip the attachment at chest height.',
      'Pin your elbows at your sides — they stay there throughout.',
      'Push the attachment down until arms are fully extended.',
      'Squeeze your triceps at the bottom.',
      'Let it rise slowly back to the start.',
    ],
    tips: [
      'Keep your elbows locked in place — don\'t let them flare out.',
      'The rope attachment allows a wider range of motion at the bottom.',
    ],
  },
  {
    id: 15, name: 'Plank', cat: 'strength', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: null,
    instructions: [
      'Place forearms on the floor, elbows under your shoulders.',
      'Extend your legs behind you, resting on your toes.',
      'Keep your body in a straight line from head to heels.',
      'Hold the position while breathing steadily.',
    ],
    tips: [
      'Don\'t let your hips sag or rise — stay flat.',
      'Squeeze your glutes and core simultaneously.',
      'Build up hold time gradually — start with 20 seconds.',
    ],
  },
  {
    id: 16, name: 'Crunches', cat: 'strength', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 20,
    instructions: [
      'Lie on your back with knees bent, feet flat on the floor.',
      'Place hands lightly behind your head.',
      'Lift your shoulder blades off the floor by contracting your abs.',
      'Lower back down with control.',
    ],
    tips: [
      'Don\'t pull on your neck — let your abs do the work.',
      'Exhale as you crunch up, inhale on the way down.',
      'Focus on quality of contraction over number of reps.',
    ],
  },
  {
    id: 17, name: 'Leg Raise', cat: 'strength', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Lie flat on your back, legs straight, hands under your lower back for support.',
      'Keeping legs straight, raise them to 90° (perpendicular to the floor).',
      'Lower them slowly until they\'re just above the floor.',
      'Repeat without letting your feet touch the ground.',
    ],
    tips: [
      'The slower the descent, the harder the exercise.',
      'If your lower back arches excessively, bend your knees slightly.',
    ],
  },
  {
    id: 18, name: 'Glute Bridge', cat: 'strength', muscle: 'glutes',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Lie on your back with knees bent, feet flat on the floor hip-width apart.',
      'Push through your heels to raise your hips toward the ceiling.',
      'Squeeze your glutes hard at the top.',
      'Lower your hips back down without fully resting.',
    ],
    tips: [
      'Keep your core braced throughout.',
      'Pause and squeeze at the top for maximum glute activation.',
      'Add a barbell across your hips to progress.',
    ],
  },
  {
    id: 19, name: 'Hip Thrust', cat: 'strength', muscle: 'glutes',
    bodyPart: 'legs', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Rest your upper back on a bench, barbell across your hips.',
      'Feet flat on the floor, hip-width apart.',
      'Drive through your heels to push your hips up until your body is parallel to the floor.',
      'Squeeze glutes hard at the top.',
      'Lower with control.',
    ],
    tips: [
      'Use a barbell pad to protect your hips.',
      'The bench height should allow 90° knee angle at the top.',
      'Drive hips straight up — avoid hyperextending your lower back.',
    ],
  },
  {
    id: 20, name: 'Cable Row', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'beginner', equipment: 'cable',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit at the cable row machine with feet on the footrests.',
      'Grab the handle with both hands, arms extended.',
      'Sit tall and pull the handle to your lower chest, driving elbows back.',
      'Squeeze your back muscles at the end of the movement.',
      'Extend arms fully to return.',
    ],
    tips: [
      'Don\'t use momentum — control the weight throughout.',
      'Keep your back upright — don\'t lean back excessively.',
    ],
  },
  // ── Cardio ────────────────────────────────────────────
  {
    id: 21, name: 'Running (Treadmill)', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Step on the treadmill and start at a slow walk speed.',
      'Gradually increase to your target running pace.',
      'Maintain an upright posture with a slight forward lean.',
      'Land mid-foot beneath your hips — not heel striking far in front.',
      'Cool down with a 5-minute walk at the end.',
    ],
    tips: [
      'Start slow and build up your pace and duration progressively.',
      'Aim for a conversational pace for steady-state cardio.',
      'Stay hydrated — keep water nearby.',
    ],
  },
  {
    id: 22, name: 'Running (Outdoor)', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Warm up with a 5-minute brisk walk.',
      'Run at a comfortable pace — you should be able to hold a conversation.',
      'Focus on a relaxed stride — land gently under your center of mass.',
      'Cool down with 5 minutes of walking followed by stretching.',
    ],
    tips: [
      'Wear proper running shoes to prevent injuries.',
      'Run against traffic so you can see oncoming vehicles.',
      'Carry water or plan your route near water fountains.',
    ],
  },
  {
    id: 23, name: 'Walking', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Walk at a brisk pace — faster than a stroll.',
      'Swing your arms naturally at your sides.',
      'Keep your head up and look forward, not down.',
      'Aim for 30+ minutes at a brisk pace.',
    ],
    tips: ['10,000 steps/day is a great daily target.', 'Walking after meals helps regulate blood sugar.'],
  },
  {
    id: 24, name: 'Cycling (Stationary)', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Adjust the seat so your leg is almost fully extended at the bottom of the pedal stroke.',
      'Set a comfortable resistance level.',
      'Pedal at a steady cadence — aim for 60–90 RPM.',
      'Keep your upper body relaxed.',
    ],
    tips: ['Higher resistance = more strength; higher cadence = more cardio.', 'Sit back on the seat — not on the tip.'],
  },
  {
    id: 25, name: 'Cycling (Outdoor)', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Wear a helmet and check your bike before riding.',
      'Start at a comfortable pace and increase intensity on hills.',
      'Use gears to maintain a consistent pedaling effort.',
      'Signal turns and follow traffic rules.',
    ],
    tips: ['Always wear a helmet.', 'Carry a small repair kit and pump.'],
  },
  {
    id: 26, name: 'Jump Rope', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Hold the rope handles with a light grip.',
      'Start jumping with both feet together at a steady pace.',
      'Keep jumps small — just enough to clear the rope (1–2 inches).',
      'Use your wrists to spin the rope, not your shoulders.',
    ],
    tips: ['Jump on a cushioned surface to protect your joints.', 'Start with 30-second rounds if you\'re new to it.'],
  },
  {
    id: 27, name: 'Burpees', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'intermediate', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Stand with feet shoulder-width apart.',
      'Drop your hands to the floor and jump your feet back to a plank.',
      'Perform a push-up (optional).',
      'Jump your feet forward to your hands.',
      'Explosively jump upward with arms overhead.',
      'Land softly and immediately go into the next rep.',
    ],
    tips: ['Pace yourself — burpees are very taxing.', 'Modify by stepping instead of jumping for a lower-impact version.'],
  },
  {
    id: 28, name: 'Mountain Climbers', cat: 'cardio', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 20,
    instructions: [
      'Start in a high plank position with arms straight.',
      'Drive one knee toward your chest, then quickly switch legs.',
      'Alternate legs in a running motion.',
      'Keep your hips level — don\'t let them rise or fall.',
    ],
    tips: ['The faster you go, the more cardio. Slower = more core work.', 'Keep your shoulders directly above your wrists.'],
  },
  {
    id: 29, name: 'Elliptical', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Step onto the elliptical and grip the handlebars.',
      'Start pedaling in a smooth, oval motion.',
      'Push and pull the handles to engage your upper body.',
      'Maintain an upright posture — don\'t lean on the machine.',
    ],
    tips: ['Going backwards engages the hamstrings and glutes more.', 'Low-impact — great for those with joint issues.'],
  },
  {
    id: 30, name: 'Swimming', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Warm up with an easy lap.',
      'Choose a stroke: freestyle, breaststroke, or backstroke.',
      'Focus on smooth technique — efficiency beats speed.',
      'Rest between laps as needed.',
    ],
    tips: ['Swimming is a full-body, zero-impact workout.', 'Bilateral breathing in freestyle helps balance your stroke.'],
  },
  {
    id: 31, name: 'Stair Climbing', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Find a staircase or use a stair climber machine.',
      'Step up one stair at a time at a brisk pace.',
      'Push through your heel as you step up.',
      'Use the rails lightly — don\'t rely on them.',
    ],
    tips: ['Taking two steps at a time increases glute activation.', 'Lean slightly forward to engage your glutes more.'],
  },
  {
    id: 32, name: 'HIIT Circuit', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'intermediate', equipment: 'bodyweight',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Choose 4–6 exercises (e.g. burpees, jump squats, mountain climbers, push-ups).',
      'Perform each exercise for 40 seconds with maximum effort.',
      'Rest for 20 seconds between exercises.',
      'Complete 3–4 rounds total.',
    ],
    tips: ['The rest period is crucial — don\'t skip it.', 'HIIT burns calories for hours after the workout (EPOC effect).'],
  },
  {
    id: 33, name: 'Box Jumps', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'intermediate', equipment: 'none',
    defaultSets: 4, defaultReps: 10,
    instructions: [
      'Stand in front of a sturdy box, feet shoulder-width apart.',
      'Swing your arms back and bend your knees.',
      'Explosively jump onto the box, landing softly with both feet.',
      'Stand fully on the box, then step down carefully.',
      'Reset and repeat.',
    ],
    tips: ['Always step down — don\'t jump down to protect your joints.', 'Start with a low box (12 inches) and progress up.'],
  },
  {
    id: 34, name: 'Rowing Machine', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Sit on the rower and strap your feet in.',
      'Grab the handle with an overhand grip.',
      'Push through your legs first, then lean back, then pull the handle to your lower chest.',
      'Return in reverse: arms forward, body forward, legs bend.',
    ],
    tips: ['60% of power comes from legs, 20% from the core, 20% from arms.', 'Keep your back straight — don\'t round it.'],
  },
  {
    id: 35, name: 'Battle Ropes', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'intermediate', equipment: 'none',
    defaultSets: 3, defaultReps: null,
    instructions: [
      'Anchor the ropes around a sturdy post.',
      'Stand with feet shoulder-width apart, knees slightly bent.',
      'Grab one end of each rope.',
      'Alternate raising each arm rapidly to create waves.',
      'Keep going for 20–30 seconds per set.',
    ],
    tips: ['Squat slightly lower for more leg engagement.', 'Try double-arm slams for a different stimulus.'],
  },
  // ── Flexibility ────────────────────────────────────────
  {
    id: 36, name: 'Yoga (Vinyasa)', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Start in Mountain Pose (standing tall) and focus on your breath.',
      'Flow through sun salutations — forward fold, plank, cobra, downward dog.',
      'Hold each pose for 3–5 breaths.',
      'Move with your breath: inhale to extend, exhale to fold.',
      'End with a 2-minute savasana (lying flat, fully relaxed).',
    ],
    tips: ['Go at your own pace — yoga is not a competition.', 'Consistency matters more than perfection in each pose.'],
  },
  {
    id: 37, name: 'Full Body Stretching', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Hold each stretch for 20–30 seconds without bouncing.',
      'Work from top to bottom: neck, shoulders, chest, back, hips, quads, hamstrings, calves.',
      'Breathe deeply and relax into each stretch on every exhale.',
      'Never stretch to the point of pain — mild discomfort is fine.',
    ],
    tips: ['Best done after a workout when muscles are warm.', 'Daily stretching dramatically improves flexibility over time.'],
  },
  {
    id: 38, name: 'Foam Rolling', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Place the foam roller under the muscle you want to target.',
      'Use your bodyweight to apply pressure.',
      'Roll slowly (1 inch per second) along the length of the muscle.',
      'When you find a tender spot, pause and hold for 20–30 seconds.',
      'Roll each muscle group for 60–90 seconds.',
    ],
    tips: ['Foam rolling before or after a workout reduces soreness.', 'Avoid rolling directly over joints or bones.'],
  },
  {
    id: 39, name: 'Pilates', cat: 'flexibility', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Lie on your back with knees bent for the starting position.',
      'Engage your core by drawing your navel toward your spine.',
      'Perform the Hundred: raise legs to 45°, pump arms up and down 100 times while breathing.',
      'Move through exercises like the Roll-Up, Leg Circle, and Single Leg Stretch.',
      'Always maintain the "pilates powerhouse" — core, glutes, and pelvic floor engaged.',
    ],
    tips: ['Quality of movement beats quantity every time in Pilates.', 'Focus on your breathing pattern — it drives the exercises.'],
  },
  {
    id: 40, name: 'Sun Salutation', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Begin in Mountain Pose — stand tall, feet together.',
      'Inhale: raise arms overhead.',
      'Exhale: fold forward, hands toward the floor.',
      'Inhale: step or jump back to Plank Pose.',
      'Exhale: lower to the floor or into Chaturanga.',
      'Inhale: lift into Cobra or Upward Dog.',
      'Exhale: push back to Downward Dog — hold for 5 breaths.',
      'Inhale: step or jump forward. Exhale: fold. Inhale: rise back to standing.',
    ],
    tips: ['Do 3–5 rounds as a warm-up or standalone practice.', 'Let your breath lead the movement — don\'t rush.'],
  },
];

function searchExercises({ q = '', bodyPart = '', cat = '', difficulty = '', equipment = '' } = {}) {
  return EXERCISES.filter(e => {
    const matchQ = !q || e.name.toLowerCase().includes(q.toLowerCase()) || (e.muscle || '').toLowerCase().includes(q.toLowerCase());
    const matchBodyPart = !bodyPart || e.bodyPart === bodyPart;
    const matchCat = !cat || e.cat === cat;
    const matchDifficulty = !difficulty || e.difficulty === difficulty;
    const matchEquipment = !equipment || e.equipment === equipment;
    return matchQ && matchBodyPart && matchCat && matchDifficulty && matchEquipment;
  });
}

module.exports = { EXERCISES, searchExercises };
