const EXERCISES = [
  // ── Strength ───────────────────────────────────────────
  {
    id: 1, name: 'Bench Press', cat: 'strength', muscle: 'chest',
    bodyPart: 'chest', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 10,
    instructions: [
      'Set up the barbell at chest height on the rack.',
      'Lie flat on the bench with your eyes directly under the bar.',
      'Grip the bar slightly wider than shoulder-width with an overhand grip.',
      'Plant your feet flat on the floor and arch your lower back slightly.',
      'Unrack the bar by straightening your arms and moving it over your chest.',
      'Lower the bar slowly to your mid-chest in a controlled manner (2–3 sec).',
      'Press the bar back up explosively to full extension without locking out hard.',
      'Re-rack the bar after completing all reps.',
    ],
    tips: [
      'Keep your shoulder blades squeezed together and pulled down throughout.',
      'Don\'t bounce the bar off your chest — control the descent.',
      'Drive your feet into the floor for leg drive and stability.',
      'Keep your wrists straight to avoid wrist strain.',
      'Use a spotter or safety bars when lifting heavy.',
    ],
  },
  {
    id: 2, name: 'Incline Dumbbell Press', cat: 'strength', muscle: 'chest',
    bodyPart: 'chest', difficulty: 'intermediate', equipment: 'dumbbell',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Set an adjustable bench to a 30–45° incline.',
      'Sit on the bench with a dumbbell in each hand resting on your thighs.',
      'Lean back and kick the dumbbells up to shoulder level, palms facing forward.',
      'Press the dumbbells up until your arms are fully extended above your upper chest.',
      'Lower the dumbbells slowly back to shoulder level.',
      'Repeat for the desired number of reps.',
    ],
    tips: [
      'A 30° incline targets the upper chest more than 45°.',
      'Keep the dumbbells in line with your upper chest, not your shoulders.',
      'Avoid flaring your elbows out more than 75°.',
      'Control the lowering phase — don\'t let gravity do the work.',
    ],
  },
  {
    id: 3, name: 'Push-up', cat: 'strength', muscle: 'chest',
    bodyPart: 'chest', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Start in a high plank position with hands slightly wider than shoulder-width.',
      'Keep your body in a straight line from head to heels — engage your core.',
      'Lower your chest toward the floor by bending your elbows at about a 45° angle.',
      'Stop just before your chest touches the floor.',
      'Push back up explosively to the starting position.',
      'Breathe in on the way down, breathe out on the way up.',
    ],
    tips: [
      'Don\'t let your hips sag or pike — keep a rigid plank position.',
      'Keep your neck neutral — don\'t drop your head.',
      'For an easier variation, drop to your knees.',
      'For harder variation, elevate your feet on a bench.',
      'Slow down the lowering phase to 3 seconds for extra difficulty.',
    ],
  },
  {
    id: 4, name: 'Pull-up', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'intermediate', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 8,
    instructions: [
      'Hang from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width.',
      'Let your arms fully extend and your shoulders relax into a dead hang.',
      'Engage your core and squeeze your shoulder blades together.',
      'Pull your chest toward the bar by driving your elbows down toward your hips.',
      'Continue until your chin clears the bar.',
      'Lower yourself slowly and under control back to the dead hang.',
    ],
    tips: [
      'Lead with your chest, not your chin.',
      'Avoid swinging or kipping unless training specifically for that.',
      'If you can\'t do a full pull-up, use an assisted machine or resistance band.',
      'Squeeze at the top for a full lat contraction.',
      'Full range of motion (complete dead hang) is essential.',
    ],
  },
  {
    id: 5, name: 'Lat Pulldown', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'beginner', equipment: 'machine',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit at the lat pulldown machine and adjust the thigh pad to secure your legs.',
      'Grip the bar wider than shoulder-width with an overhand grip.',
      'Lean back slightly (about 15–20°) to maintain proper form.',
      'Pull the bar down toward your upper chest by driving your elbows toward the floor.',
      'Squeeze your lats at the bottom of the movement.',
      'Slowly return the bar to the starting position with your arms fully extended.',
    ],
    tips: [
      'Pull the bar to your upper chest, not behind your neck.',
      'Lead with your elbows, not your hands.',
      'Avoid using momentum — control the full range of motion.',
      'A slight lean back is normal; don\'t lean back excessively.',
      'Squeeze your shoulder blades together at the bottom.',
    ],
  },
  {
    id: 6, name: 'Bent-Over Row', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 10,
    instructions: [
      'Stand with feet shoulder-width apart, holding the barbell with an overhand grip.',
      'Hinge at the hips until your torso is about 45° to parallel with the floor.',
      'Keep your back flat and core engaged throughout the movement.',
      'Let the bar hang at arm\'s length toward the floor.',
      'Pull the bar toward your lower ribcage / belly button, driving elbows back.',
      'Squeeze your back muscles at the top, then lower the bar in a controlled manner.',
    ],
    tips: [
      'Keep your lower back neutral — do not round your spine.',
      'Think about pulling your elbows rather than your hands.',
      'A slight knee bend is acceptable to protect the lower back.',
      'Use straps if grip is failing before your back muscles.',
      'Keep the bar close to your body throughout the movement.',
    ],
  },
  {
    id: 7, name: 'Deadlift', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'advanced', equipment: 'barbell',
    defaultSets: 4, defaultReps: 5,
    instructions: [
      'Stand with feet hip-width apart, toes pointing slightly outward.',
      'Position the barbell over your mid-foot (about 1 inch from your shins).',
      'Hinge at the hips and bend the knees to grip the bar just outside your legs.',
      'Take a big breath, brace your core (valsalva maneuver), and set a flat back.',
      'Push the floor away with your legs while simultaneously lifting the bar.',
      'Keep the bar in contact with your legs as it passes the knees.',
      'Lock out at the top by squeezing your glutes and standing tall.',
      'Lower the bar under control back to the floor.',
    ],
    tips: [
      'The deadlift is a push, not a pull — think of pushing the floor away.',
      'Never round your lower back under load.',
      'Engage your lats before lifting to keep the bar close.',
      'Use a mixed grip or hook grip for heavier loads.',
      'Start light and master form before adding weight.',
    ],
  },
  {
    id: 8, name: 'Barbell Squat', cat: 'strength', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 4, defaultReps: 8,
    instructions: [
      'Set the barbell at shoulder height on a squat rack.',
      'Step under the bar and position it on your upper traps (high bar) or rear delts (low bar).',
      'Unrack the bar, step back, and stand with feet shoulder-width apart.',
      'Toes should point out at about 30°.',
      'Take a deep breath, brace your core, and begin the squat by breaking at the hips and knees simultaneously.',
      'Lower until your thighs are at least parallel to the floor.',
      'Drive back up through your heels, maintaining chest up throughout.',
      'Lock out at the top by squeezing your glutes.',
    ],
    tips: [
      'Keep your chest up and avoid caving your knees inward.',
      'Your knees should track over your toes throughout the movement.',
      'Depth is important — aim for at least parallel.',
      'Keep your core braced — no breath until the rep is complete.',
      'Use weightlifting shoes or a heel raise if ankle mobility is limited.',
    ],
  },
  {
    id: 9, name: 'Leg Press', cat: 'strength', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'machine',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit in the leg press machine with your back and head flat against the padded support.',
      'Place your feet hip-width apart on the platform.',
      'Release the safety handles and bend your knees to lower the platform.',
      'Lower until your knees form approximately a 90° angle.',
      'Press the platform back up by extending your legs — do not lock out your knees.',
      'Repeat for the desired number of reps, then re-engage the safety handles.',
    ],
    tips: [
      'Don\'t let your lower back lift off the seat at the bottom.',
      'Avoid locking your knees at full extension.',
      'Higher foot placement emphasizes the glutes and hamstrings; lower placement targets the quads.',
      'Keep your feet flat on the platform throughout.',
      'Control the lowering phase — don\'t let the weight drop.',
    ],
  },
  {
    id: 10, name: 'Lunges', cat: 'strength', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Stand tall with feet together and hands on your hips (or holding dumbbells at your sides).',
      'Step forward with one foot about 2–3 feet.',
      'Lower your body until your front thigh is parallel to the floor and rear knee nearly touches the ground.',
      'Your front knee should stay directly above your ankle.',
      'Push through your front heel to return to the starting position.',
      'Alternate legs for each rep.',
    ],
    tips: [
      'Keep your torso upright throughout — don\'t lean forward.',
      'Don\'t let your front knee cave inward.',
      'Start with bodyweight before adding dumbbells.',
      'For a walking lunge variation, step forward continuously.',
      'Engage your core to maintain balance.',
    ],
  },
  {
    id: 11, name: 'Shoulder Press', cat: 'strength', muscle: 'shoulders',
    bodyPart: 'shoulders', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 10,
    instructions: [
      'Sit on a bench with back support or stand with feet shoulder-width apart.',
      'Hold the barbell at shoulder height with hands slightly wider than shoulder-width.',
      'Elbows should be slightly in front of the bar.',
      'Press the bar overhead until your arms are fully extended.',
      'Lower the bar back to shoulder height in a controlled manner.',
      'Repeat for the desired number of reps.',
    ],
    tips: [
      'Avoid excessive arching of the lower back — keep your core tight.',
      'The bar should travel in a straight vertical path.',
      'Don\'t press the bar in front of your face — press it over your head.',
      'For a dumbbell variation, the range of motion and shoulder activation are slightly different.',
      'Control the descent — don\'t drop the weight.',
    ],
  },
  {
    id: 12, name: 'Lateral Raise', cat: 'strength', muscle: 'shoulders',
    bodyPart: 'shoulders', difficulty: 'beginner', equipment: 'dumbbell',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Stand with a dumbbell in each hand, arms at your sides, palms facing in.',
      'With a slight bend in your elbows, raise both arms out to the sides.',
      'Continue raising until your arms are parallel to the floor (shoulder height).',
      'Pause briefly at the top, then lower slowly back to your sides.',
      'Keep the movement controlled — avoid swinging.',
    ],
    tips: [
      'Use lighter weight — lateral raises are often done with too much weight and momentum.',
      'Think of pouring a jug of water at the top — pinky finger slightly higher than thumb.',
      'Keep your torso still throughout — no body swinging.',
      'The lowering phase (eccentric) is just as important as raising.',
      'A slight forward lean can shift focus to the posterior head of the deltoid.',
    ],
  },
  {
    id: 13, name: 'Bicep Curl', cat: 'strength', muscle: 'biceps',
    bodyPart: 'arms', difficulty: 'beginner', equipment: 'dumbbell',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Stand with a dumbbell in each hand, arms fully extended, palms facing forward.',
      'Keep your upper arms stationary against your torso.',
      'Curl the dumbbells upward toward your shoulders by contracting your biceps.',
      'Rotate your palms up as you curl (supinate) if starting with a neutral grip.',
      'Squeeze your biceps at the top of the movement.',
      'Slowly lower the dumbbells back to the starting position.',
    ],
    tips: [
      'Keep your elbows from swinging forward — they should stay at your sides.',
      'Don\'t use momentum or swing your back.',
      'Full range of motion means fully extending at the bottom.',
      'Alternate arms or curl both simultaneously.',
      'Concentration curls (seated, elbow on thigh) provide an excellent peak contraction.',
    ],
  },
  {
    id: 14, name: 'Tricep Pushdown', cat: 'strength', muscle: 'triceps',
    bodyPart: 'arms', difficulty: 'beginner', equipment: 'cable',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Stand at a cable machine with the pulley set to a high position.',
      'Attach a straight bar or rope handle.',
      'Grip the attachment with both hands, elbows bent at 90° and tucked at your sides.',
      'Keeping your upper arms stationary, push the attachment down until your arms are fully extended.',
      'Squeeze your triceps at the bottom.',
      'Slowly return to the starting position with elbows at 90°.',
    ],
    tips: [
      'Keep your elbows pinned to your sides throughout.',
      'Don\'t lean forward excessively — stay mostly upright.',
      'A rope attachment allows you to spread at the bottom for a better contraction.',
      'Control the weight on the way back up — resist the cable.',
      'Don\'t use your body weight to push the weight down.',
    ],
  },
  {
    id: 15, name: 'Plank', cat: 'strength', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: null,
    instructions: [
      'Start in a push-up position, then lower onto your forearms.',
      'Your elbows should be directly beneath your shoulders.',
      'Keep your body in a perfectly straight line from head to heels.',
      'Engage your core by drawing your navel toward your spine.',
      'Squeeze your glutes and keep your hips level.',
      'Hold the position for the target duration (30–60 seconds to start).',
    ],
    tips: [
      'Don\'t let your hips rise or sag — both break the straight line.',
      'Keep your neck neutral — look at the floor about 12 inches in front of you.',
      'Breathe steadily — don\'t hold your breath.',
      'Start with 20–30 second holds and build up over time.',
      'If this is too hard, drop to your knees initially.',
    ],
  },
  {
    id: 16, name: 'Crunches', cat: 'strength', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 20,
    instructions: [
      'Lie flat on your back with knees bent at 90° and feet flat on the floor.',
      'Place your hands lightly behind your head — don\'t pull on your neck.',
      'Engage your core and curl your upper body toward your knees.',
      'Only your shoulder blades should lift off the floor — this is not a full sit-up.',
      'Squeeze your abs at the top, then lower back down slowly.',
      'Keep tension in your abs throughout — don\'t fully relax at the bottom.',
    ],
    tips: [
      'Focus on shortening the distance between your ribs and hips.',
      'Exhale as you crunch up, inhale as you lower.',
      'Look at the ceiling, not at your knees — keeps the neck neutral.',
      'Avoid pulling your head with your hands.',
      'Slow down the tempo for increased difficulty.',
    ],
  },
  {
    id: 17, name: 'Leg Raise', cat: 'strength', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Lie flat on your back with legs extended and hands placed under your lower back / glutes for support.',
      'Press your lower back into the floor.',
      'Keeping legs straight (or slightly bent), raise them up toward the ceiling until they\'re at 90°.',
      'Slowly lower your legs back down — stop just before they touch the floor.',
      'Repeat without letting your legs rest on the floor between reps.',
    ],
    tips: [
      'Go slower on the lowering phase for maximum core engagement.',
      'If you feel lower back pain, bend your knees slightly.',
      'Keep breathing — don\'t hold your breath.',
      'For a harder variation, hang from a pull-up bar and raise your legs.',
      'Pressing your lower back down is essential to protect the spine.',
    ],
  },
  {
    id: 18, name: 'Glute Bridge', cat: 'strength', muscle: 'glutes',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Lie flat on your back with knees bent at 90°, feet flat on the floor hip-width apart.',
      'Arms by your sides, palms facing down.',
      'Drive through your heels to raise your hips off the floor.',
      'Squeeze your glutes hard at the top — your body should form a straight line from shoulders to knees.',
      'Hold for 1–2 seconds at the top.',
      'Lower your hips back to the floor in a controlled manner.',
    ],
    tips: [
      'Don\'t use your lower back to drive the movement — focus on the glutes.',
      'Press your heels firmly into the floor throughout.',
      'Add resistance by placing a barbell or dumbbell across your hips.',
      'For single-leg variation, extend one leg while bridging with the other.',
      'Squeeze at the top for a full 2 seconds to maximize glute activation.',
    ],
  },
  {
    id: 19, name: 'Hip Thrust', cat: 'strength', muscle: 'glutes',
    bodyPart: 'legs', difficulty: 'intermediate', equipment: 'barbell',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit on the floor with your upper back against a bench, knees bent, feet flat.',
      'Roll a barbell over your hips (use a pad for comfort).',
      'Plant your feet firmly and about hip-width apart.',
      'Drive your hips up by squeezing your glutes until your torso is parallel to the floor.',
      'Your shins should be vertical at the top position.',
      'Lower your hips back to just above the floor and repeat.',
    ],
    tips: [
      'Keep your chin tucked — look at your belly button, not the ceiling.',
      'Avoid hyperextending your lower back at the top.',
      'The barbell pad makes this significantly more comfortable.',
      'Feet placement matters — experiment to find what activates your glutes best.',
      'This is the best exercise for glute development — progressive overload is key.',
    ],
  },
  {
    id: 20, name: 'Cable Row', cat: 'strength', muscle: 'back',
    bodyPart: 'back', difficulty: 'beginner', equipment: 'cable',
    defaultSets: 3, defaultReps: 12,
    instructions: [
      'Sit at a seated cable row machine with your feet on the footrests.',
      'Grab the handle with both hands and sit upright with a slight lean forward.',
      'Pull the handle toward your lower abdomen by driving your elbows back.',
      'Squeeze your shoulder blades together at the end of the pull.',
      'Slowly extend your arms to return to the starting position.',
      'Lean slightly forward with each rep — don\'t use excessive torso swing.',
    ],
    tips: [
      'Don\'t round your lower back — keep your spine neutral.',
      'Focus on squeezing your back, not just pulling with your arms.',
      'A close-grip handle targets the middle back; a wide grip targets the lats more.',
      'Full stretch at the front is important for complete muscle development.',
      'Control the eccentric (extension) phase — don\'t let the cable snap back.',
    ],
  },

  // ── Cardio ─────────────────────────────────────────────
  {
    id: 21, name: 'Running (Treadmill)', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Start the treadmill at a slow walk to warm up for 3–5 minutes.',
      'Gradually increase the speed to your target running pace.',
      'Land with a mid-foot strike, not on your heels.',
      'Keep your arms at 90° and swing them front to back — not across your body.',
      'Maintain an upright posture with a slight forward lean from the ankles.',
      'Cool down by slowing to a walk for the last 3–5 minutes.',
    ],
    tips: [
      'Use the incline (1–2%) to simulate outdoor running resistance.',
      'Don\'t hold onto the handrails — it reduces calorie burn and disrupts form.',
      'Breathe rhythmically — try to breathe every 2–3 steps.',
      'Monitor your heart rate if training in specific zones.',
    ],
  },
  {
    id: 22, name: 'Running (Outdoor)', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Warm up with a 5-minute brisk walk before running.',
      'Start at a conversational pace — you should be able to speak in short sentences.',
      'Keep your posture upright with a slight forward lean from your ankles.',
      'Arms should be bent at 90° and swing naturally forward and back.',
      'Land with a mid-foot strike under your hips.',
      'End your run with a 5-minute cool-down walk and stretching.',
    ],
    tips: [
      'Start with the run-walk method if you\'re a beginner (1 min run, 2 min walk).',
      'Wear proper running shoes with appropriate support for your foot type.',
      'Run on varied surfaces — grass and trails are easier on joints than concrete.',
      'Stay hydrated — drink water before, during (if over 30 min), and after.',
    ],
  },
  {
    id: 23, name: 'Walking', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Stand upright with your shoulders relaxed and core lightly engaged.',
      'Swing your arms naturally at your sides.',
      'Take comfortable strides — heel strikes first for walking (unlike running).',
      'Maintain a brisk pace — aim for 100 steps per minute for health benefits.',
      'Keep your gaze forward, not looking down at the ground.',
    ],
    tips: [
      'Aim for at least 30 minutes of brisk walking per day.',
      '10,000 steps a day is a good daily target.',
      'Walking after meals helps with digestion and blood sugar control.',
      'Adding hills or incline increases the intensity significantly.',
      'Proper footwear reduces joint stress on longer walks.',
    ],
  },
  {
    id: 24, name: 'Cycling (Stationary)', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Adjust the seat height so there is a slight bend in your knee at the bottom of the pedal stroke.',
      'Adjust handlebar height for a comfortable reach.',
      'Start pedaling at a low resistance to warm up for 5 minutes.',
      'Increase resistance to a challenging but sustainable level.',
      'Keep your cadence smooth and consistent — aim for 70–90 RPM for steady-state cardio.',
      'Cool down for 5 minutes at low resistance.',
    ],
    tips: [
      'Don\'t hunch your back — keep your spine neutral and shoulders relaxed.',
      'Push through the heel of your foot, not just the toes.',
      'Increase resistance rather than just increasing speed for better training.',
      'Spinning classes are great for motivation and structure.',
    ],
  },
  {
    id: 25, name: 'Cycling (Outdoor)', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Adjust your bike so the seat allows a slight knee bend at the bottom of the pedal stroke.',
      'Always wear a properly fitting helmet.',
      'Warm up for 5 minutes at an easy pace.',
      'Maintain a cadence of 70–90 RPM in an appropriate gear.',
      'Use your gears effectively — lower gears for climbing, higher gears for flat roads.',
      'Cool down with easy pedaling for 5 minutes.',
    ],
    tips: [
      'Gear down before you reach the hill — don\'t wait until you\'re struggling.',
      'Keep your elbows slightly bent to absorb road vibrations.',
      'Signal your turns and be predictable to other road users.',
      'Stay hydrated on longer rides — drink every 15–20 minutes.',
    ],
  },
  {
    id: 26, name: 'Jump Rope', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Choose a rope length — when you stand on the middle, handles should reach your armpits.',
      'Hold the handles at hip level with elbows close to your sides.',
      'Start spinning the rope from your wrists, not your arms.',
      'Jump just high enough to clear the rope — about 1 inch off the ground.',
      'Land softly on the balls of your feet with knees slightly bent.',
      'Start with 30-second intervals and build up.',
    ],
    tips: [
      'Jump on a soft surface like a mat or rubber floor — easier on joints.',
      'Keep your core engaged and posture upright.',
      'Master the basic jump before trying double-unders or crossovers.',
      'Jump rope is one of the most efficient cardio exercises — 10 minutes = 30 min of jogging.',
    ],
  },
  {
    id: 27, name: 'Burpees', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'intermediate', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 15,
    instructions: [
      'Stand with feet shoulder-width apart.',
      'Drop your hands to the floor and jump or step your feet back into a plank position.',
      'Perform a push-up (optional but recommended).',
      'Jump or step your feet back toward your hands.',
      'Explosively jump upward with arms overhead.',
      'Land softly with knees bent and immediately begin the next rep.',
    ],
    tips: [
      'Scale by removing the push-up or the jump at the top.',
      'Keep your core tight throughout to protect your lower back.',
      'Focus on the landing — absorb through your legs, not your joints.',
      'For HIIT, go all out for 20–30 seconds; for conditioning, maintain steady pace.',
    ],
  },
  {
    id: 28, name: 'Mountain Climbers', cat: 'cardio', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'bodyweight',
    defaultSets: 3, defaultReps: 20,
    instructions: [
      'Start in a high plank position with hands directly under your shoulders.',
      'Keep your hips level and core engaged.',
      'Drive your right knee toward your chest as far as possible.',
      'Quickly switch legs — drive the right foot back while bringing the left knee forward.',
      'Continue alternating legs rapidly.',
      'Each knee drive counts as one rep (or count both as one rep if preferred).',
    ],
    tips: [
      'Keep your hips from bouncing up and down.',
      'Breathe steadily — don\'t hold your breath.',
      'For a slower core focus, pause with each knee forward.',
      'For cardio, increase the pace to make it more dynamic.',
      'Keep your shoulders stacked directly over your hands.',
    ],
  },
  {
    id: 29, name: 'Elliptical', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Step onto the elliptical and grip the handles.',
      'Start pedaling at a low resistance to warm up.',
      'Push the handles forward as you push your foot down.',
      'Maintain an upright posture — don\'t lean on the handles.',
      'Increase resistance and/or incline to challenge yourself.',
      'Cool down by reducing resistance for the last 5 minutes.',
    ],
    tips: [
      'The elliptical is low impact — great for joints while still burning calories.',
      'Don\'t use the handles if you want to engage your core more.',
      'Going backward on the elliptical emphasizes the glutes and hamstrings.',
      'Aim for a steady pace — monitor your heart rate if possible.',
    ],
  },
  {
    id: 30, name: 'Swimming', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Begin with a warm-up — easy laps of freestyle or backstroke.',
      'Focus on technique before speed — inefficient technique wastes energy.',
      'For freestyle: rotate your body, reach long, pull water from in front of your chest toward your hip.',
      'Kick from your hips with a flutter kick — your legs should be mostly straight.',
      'Breathe by rotating your head to the side every 2–3 strokes.',
      'Cool down with easy laps and stretching after.',
    ],
    tips: [
      'Swimming is one of the most complete full-body workouts with zero joint impact.',
      'A swim cap reduces drag and keeps hair out of your face.',
      'Goggles are essential for open-eye swimming.',
      'Pool intervals (sprint a lap, rest a lap) dramatically improve fitness.',
    ],
  },
  {
    id: 31, name: 'Stair Climbing', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Use a stair climber machine or find a set of stairs.',
      'Set the machine to a comfortable pace and start stepping.',
      'Keep your weight over your foot — don\'t lean heavily on the handrails.',
      'Step fully with each foot — don\'t half-step.',
      'Maintain an upright posture with your core engaged.',
      'Cool down by slowing your pace for the last 3–5 minutes.',
    ],
    tips: [
      'Stair climbing burns significantly more calories than walking on flat ground.',
      'Lightly touch the handrails for balance only — don\'t bear weight on them.',
      'Taking two steps at a time increases glute activation.',
      'Great for building leg endurance and cardiovascular fitness simultaneously.',
    ],
  },
  {
    id: 32, name: 'HIIT Circuit', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'intermediate', equipment: 'bodyweight',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Choose 4–6 exercises (e.g., burpees, mountain climbers, jump squats, push-ups, high knees).',
      'Warm up for 5 minutes.',
      'Work at maximum effort for 20–40 seconds per exercise.',
      'Rest for 10–20 seconds between exercises.',
      'Complete 3–5 rounds of the circuit.',
      'Cool down and stretch for 5–10 minutes.',
    ],
    tips: [
      'The key to HIIT is giving maximum effort during work periods.',
      'Start with longer rest periods (2:1 rest:work) if you\'re new to HIIT.',
      'HIIT sessions should be limited to 2–3 times per week due to high intensity.',
      'The afterburn effect (EPOC) means you continue burning calories post-workout.',
    ],
  },
  {
    id: 33, name: 'Box Jumps', cat: 'cardio', muscle: 'legs',
    bodyPart: 'legs', difficulty: 'intermediate', equipment: 'none',
    defaultSets: 4, defaultReps: 10,
    instructions: [
      'Stand in front of a sturdy box or platform at a comfortable height.',
      'Stand with feet shoulder-width apart, arms at your sides.',
      'Swing your arms back and bend your knees to load the jump.',
      'Explosively swing your arms forward and jump onto the box.',
      'Land softly with both feet flat on the box, knees slightly bent.',
      'Stand up fully, then step (don\'t jump) back down to the floor.',
    ],
    tips: [
      'Always step down — jumping down puts excessive impact on your joints.',
      'Start with a lower box and increase height as you improve.',
      'Land softly — like you\'re trying not to make noise.',
      'Box jumps are explosive — allow full recovery between sets.',
      'Ensure the box is stable and won\'t tip when you land.',
    ],
  },
  {
    id: 34, name: 'Rowing Machine', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'machine',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Sit on the rowing machine seat and secure your feet in the footrests.',
      'Grip the handle with both hands, arms extended, and lean slightly forward.',
      'Begin the stroke by driving through your legs (legs first — 60% of power).',
      'As your legs straighten, lean back slightly and pull the handle toward your lower chest.',
      'Return: arms extend first, then lean forward, then bend your knees to slide back.',
      'Maintain a smooth, continuous rhythm.',
    ],
    tips: [
      'The rowing sequence is: legs → body → arms on the drive; arms → body → legs on recovery.',
      'Don\'t round your lower back — maintain a neutral spine.',
      'A common mistake is pulling with the arms first — power comes from the legs.',
      'Aim for 24–30 strokes per minute for steady-state; 32+ for high intensity.',
      'Rowing is one of the few exercises that works arms, legs, and core simultaneously.',
    ],
  },
  {
    id: 35, name: 'Battle Ropes', cat: 'cardio', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'intermediate', equipment: 'none',
    defaultSets: 3, defaultReps: null,
    instructions: [
      'Anchor the rope around a sturdy post and stand at the free end.',
      'Hold one end of the rope in each hand with a firm grip.',
      'Stand with feet shoulder-width apart, knees slightly bent, core engaged.',
      'Alternate raising and lowering each arm rapidly to create a wave pattern.',
      'Work for 20–30 seconds at full intensity.',
      'Rest for 30–60 seconds and repeat.',
    ],
    tips: [
      'Stand far enough from the anchor so there\'s some tension in the rope.',
      'Use your whole body — legs, hips, and core contribute power.',
      'Try different patterns: alternating waves, double waves, circles.',
      'Battle ropes give an excellent metabolic conditioning workout.',
    ],
  },

  // ── Flexibility ────────────────────────────────────────
  {
    id: 36, name: 'Yoga (Vinyasa)', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Start in Mountain Pose (Tadasana) — stand tall, feet together, arms at sides.',
      'Flow through a Sun Salutation: Forward Fold → Plank → Chaturanga → Upward Dog → Downward Dog.',
      'Hold each pose for 3–5 breaths before transitioning.',
      'Link breath with movement — inhale to expand, exhale to fold or contract.',
      'End in Savasana (Corpse Pose) for 5 minutes to integrate the practice.',
    ],
    tips: [
      'Never force a stretch — yoga should never cause sharp pain.',
      'Use blocks and straps to modify poses to your flexibility level.',
      'Consistency matters more than intensity — even 15 min/day has benefits.',
      'Focus on your breath — it\'s the anchor of any yoga practice.',
    ],
  },
  {
    id: 37, name: 'Full Body Stretching', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Begin with neck rolls — slowly roll your head from side to side.',
      'Chest stretch: clasp hands behind your back and squeeze your shoulder blades together.',
      'Hamstring stretch: sit on the floor with legs extended, reach toward your toes.',
      'Hip flexor stretch: kneel on one knee with the other foot forward (lunge position). Push hips forward.',
      'Quad stretch: stand on one foot, pull the other heel toward your glutes.',
      'Spinal twist: lie on your back, cross one knee over the body and look the other way.',
      'Hold each stretch for 20–30 seconds. Breathe deeply.',
    ],
    tips: [
      'Stretch when muscles are warm — ideally after a workout.',
      'Never bounce during a stretch — hold it steadily.',
      'Breathe into tight areas — tension releases on the exhale.',
      'Regular stretching improves posture, reduces injury risk, and aids recovery.',
    ],
  },
  {
    id: 38, name: 'Foam Rolling', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Place the foam roller under the target muscle group.',
      'Use your body weight to apply gentle pressure to the roller.',
      'Slowly roll the muscle back and forth, covering the full length.',
      'When you find a tender spot, pause and hold for 20–30 seconds.',
      'Continue rolling until the area feels less tense.',
      'Spend 60–90 seconds on each major muscle group.',
    ],
    tips: [
      'Don\'t roll directly on joints or bony areas.',
      'Start with gentle pressure and increase as your tolerance improves.',
      'Foam rolling before a workout reduces muscle stiffness; after reduces soreness.',
      'Avoid rolling the lower back directly — roll the glutes and thoracic spine instead.',
      'Consistent foam rolling improves mobility and reduces injury risk over time.',
    ],
  },
  {
    id: 39, name: 'Pilates', cat: 'flexibility', muscle: 'core',
    bodyPart: 'core', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Begin in the Pilates neutral spine position — lying on your back, knees bent, feet flat.',
      'Engage your deep core muscles by drawing your navel gently toward your spine.',
      'For the Hundred: lift your head and shoulders, extend arms, and pump them up and down while breathing in for 5 counts, out for 5 counts.',
      'For the Roll-up: lie flat, slowly roll up vertebra by vertebra to a seated position.',
      'For Leg Circles: lift one leg and draw circles with your foot.',
      'Move slowly and with full control — Pilates is about precision, not speed.',
    ],
    tips: [
      'Core engagement is constant throughout all Pilates exercises.',
      'Focus on quality of movement, not quantity.',
      'Pilates is excellent for posture correction, back pain relief, and core strength.',
      'A mat class is great for beginners before progressing to Reformer Pilates.',
    ],
  },
  {
    id: 40, name: 'Sun Salutation', cat: 'flexibility', muscle: 'full body',
    bodyPart: 'full body', difficulty: 'beginner', equipment: 'none',
    defaultSets: null, defaultReps: null,
    instructions: [
      'Stand in Mountain Pose (Tadasana) — feet together, arms at sides.',
      'Inhale: sweep arms overhead (Urdhva Hastasana).',
      'Exhale: fold forward from the hips (Uttanasana).',
      'Inhale: halfway lift — flat back, fingertips to shins (Ardha Uttanasana).',
      'Exhale: step or jump back to Plank Pose.',
      'Lower slowly to the floor (Chaturanga Dandasana).',
      'Inhale: Upward Facing Dog — chest up, thighs off floor.',
      'Exhale: Downward Facing Dog — hold for 3–5 breaths.',
      'Step or jump forward, fold, then inhale to rise back to standing.',
      'Repeat 4–8 rounds.',
    ],
    tips: [
      'Link every movement to a breath.',
      'Start slowly — the Sun Salutation is a complete warm-up sequence.',
      'Modify as needed: bend your knees in forward folds, use knees-down in Chaturanga.',
      'Regular Sun Salutations improve flexibility, strength, and mental focus.',
    ],
  },
];

export function getByCategory(cat) {
  return EXERCISES.filter(e => e.cat === cat);
}

export function findExercise(name) {
  return EXERCISES.find(e => e.name.toLowerCase() === name.toLowerCase());
}

export function searchExercises({ q = '', bodyPart = '', cat = '', difficulty = '', equipment = '' }) {
  return EXERCISES.filter(e => {
    const matchQ = !q || e.name.toLowerCase().includes(q.toLowerCase()) || e.muscle.toLowerCase().includes(q.toLowerCase());
    const matchBodyPart = !bodyPart || e.bodyPart === bodyPart;
    const matchCat = !cat || e.cat === cat;
    const matchDifficulty = !difficulty || e.difficulty === difficulty;
    const matchEquipment = !equipment || e.equipment === equipment;
    return matchQ && matchBodyPart && matchCat && matchDifficulty && matchEquipment;
  });
}

export default EXERCISES;
